### ISSUE TITLE
T4 and T5 tokens for PVP gear

### ISSUE THREAD

**Issue by coneone** [verkkila/AppearanceCollectionTooltip#2]
Hi!

T4 and T5 tokens can be exchanged for either PVE or PVP gear sets, but the addon only takes into account PVE gear when checking for the "Collected" tooltip on the token.

Example:
![imagen](https://github.com/verkkila/AppearanceCollectionTooltip/assets/5948571/a090b5d3-8360-4443-a7c4-b79bb31887ca)
![imagen](https://github.com/verkkila/AppearanceCollectionTooltip/assets/5948571/5b68d854-6d9d-405e-8aa1-917752bb7a4e)

P.S.: Excellent addon!

**Comment by verkkila** [comment]
Oh interesting, wasn't aware of that. Nevertheless I will be adding a special tooltip for T4, T5 and T6 tokens with information for both PvE and PvP pieces.  
I will update this issue when it's been implemented, tested & published.

Thanks for the infomation & glad you enjoy the addon!

**Comment by verkkila** [comment]
PvP item information has been added in 1.0.6 which should be available on Curse soon, will close this once that happens.
![ACT_MultiTooltip_1_0_6](https://github.com/verkkila/AppearanceCollectionTooltip/assets/14833706/c1721542-7705-43f1-9f6a-2ddfb330256e)

**Comment by coneone** [comment]
Works perfectly, thanks!
